name: forms
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.2

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  go_router: ^14.8.1
  intl: ^0.20.2
  cloud_firestore: ^5.6.5
  firebase_core: ^3.12.1
  share_plus: ^10.1.4
  url_launcher: ^6.1.11
  fl_chart: ^0.70.2
  sqflite: ^2.0.0+4
  path: ^1.8.0
  connectivity_plus: ^6.1.3
  firebase_auth: ^5.5.1
  google_sign_in: ^6.2.2
  flutter_facebook_auth: ^7.1.1
  provider: ^6.0.5
  animate_do: ^4.2.0
  sign_in_button: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  
flutter:
  uses-material-design: true
  assets:
    - assets/images/competitive_analysis.jpg
    - assets/images/course-evaluation.jpg
    - assets/images/customer-expectation-survey.jpg
    - assets/images/customer-survey.png
    - assets/images/data-analysis2.jpg
    - assets/images/entertainment_survey.jpg
    - assets/images/interview-talk.jpg
    - assets/images/invitation-portal.png
    - assets/images/new_product.jpg
    - assets/images/post_event_survey_back_hubble.jpg
    - assets/images/post_event_survey_front.jpg
    - assets/images/product-pricing-survey.jpg
    - assets/images/quiz-portal.png
    - assets/images/registration-portal.png
    - assets/images/remote_learning.jpg
    - assets/images/survey-portal.png
    - assets/images/teacher_feedback.jpg
    - assets/images/vacation.jpg
    - assets/images/background.png
    - assets/images/login-background2.png