// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHOWkp1M70UzRsyzMoH-1nv4asXAx1gLM',
    appId: '1:555779524183:web:3a996c148685fa7ea64512',
    messagingSenderId: '555779524183',
    projectId: 'encuesta-62cf6',
    authDomain: 'encuesta-62cf6.firebaseapp.com',
    storageBucket: 'encuesta-62cf6.firebasestorage.app',
    measurementId: 'G-R5DNMX40B6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHxphVphJ80EHAHy9mzcxgMokUl2aq3Sw',
    appId: '1:555779524183:android:73d8b702686c133ca64512',
    messagingSenderId: '555779524183',
    projectId: 'encuesta-62cf6',
    storageBucket: 'encuesta-62cf6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAH3xcWKIcpLvZPN3nW9pwhR9LTF-UDB54',
    appId: '1:555779524183:ios:c1125fddf1ffd694a64512',
    messagingSenderId: '555779524183',
    projectId: 'encuesta-62cf6',
    storageBucket: 'encuesta-62cf6.firebasestorage.app',
    androidClientId: '555779524183-dcdffn64jd3kgdtcij4oa31e6p87me41.apps.googleusercontent.com',
    iosClientId: '555779524183-oej2qd1r09bo2tcu38il46hh4v9hvuie.apps.googleusercontent.com',
    iosBundleId: 'com.example.forms',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAH3xcWKIcpLvZPN3nW9pwhR9LTF-UDB54',
    appId: '1:555779524183:ios:c1125fddf1ffd694a64512',
    messagingSenderId: '555779524183',
    projectId: 'encuesta-62cf6',
    storageBucket: 'encuesta-62cf6.firebasestorage.app',
    androidClientId: '555779524183-dcdffn64jd3kgdtcij4oa31e6p87me41.apps.googleusercontent.com',
    iosClientId: '555779524183-oej2qd1r09bo2tcu38il46hh4v9hvuie.apps.googleusercontent.com',
    iosBundleId: 'com.example.forms',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHOWkp1M70UzRsyzMoH-1nv4asXAx1gLM',
    appId: '1:555779524183:web:d3a3c40f2d335284a64512',
    messagingSenderId: '555779524183',
    projectId: 'encuesta-62cf6',
    authDomain: 'encuesta-62cf6.firebaseapp.com',
    storageBucket: 'encuesta-62cf6.firebasestorage.app',
    measurementId: 'G-S4WP12YZTM',
  );

}